# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-28 14:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctflex', '0003_auto_20160223_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='problems',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='unread_announcements',
        ),
        migrations.RemoveField(
            model_name='window',
            name='code',
        ),
        migrations.AddField(
            model_name='window',
            name='codename',
            field=models.CharField(default='nothappening', help_text='Non-user-facing human-readable identifier for window', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^\\w*$', 'Only alphanumeric characters and underscores are allowed.')]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
