# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-28 22:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctflex', '0004_auto_20160228_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ctfproblem',
            old_name='dynamic',
            new_name='generator',
        ),
        migrations.AlterField(
            model_name='competitor',
            name='background',
            field=models.CharField(choices=[('M', 'Middle School Student'), ('H', 'High School Student'), ('O', 'Other (ineligible to win prizes)')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='country',
            field=models.CharField(choices=[('US', 'United States'), ('OT', 'Other (ineligible to win prizes)')], default='US', max_length=2),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='first_name',
            field=models.CharField(default='Mysterious', max_length=30),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='last_name',
            field=models.CharField(default='Competitor', max_length=30),
        ),
        migrations.AlterField(
            model_name='window',
            name='codename',
            field=models.CharField(help_text='Human-readable identifier', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^\\w*$Only alphanumeric characters and underscores are allowed.')]),
        ),
    ]
