# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-27 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ctflex', '0004_auto_20160326_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
