# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-03 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctflex', '0005_auto_20160326_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctflex.Team'),
        ),
    ]
