# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-03 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctflex', '0006_auto_20160402_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctfproblem',
            name='points',
            field=models.IntegerField(),
        ),
    ]
