# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-28 23:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctflex', '0006_auto_20160228_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='window',
            name='codename',
            field=models.CharField(help_text='Human-readable identifier', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(code='word_characters', message='Only alphanumeric characters and underscores are allowed.', regex='^\\w*$')]),
        ),
    ]
