# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-03 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctflex', '0007_auto_20160402_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctfproblem',
            name='description_html',
        ),
        migrations.RemoveField(
            model_name='ctfproblem',
            name='hint_html',
        ),
    ]
