# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 01:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ctflex', '0007_auto_20160228_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='background',
            field=models.CharField(choices=[('M', 'Middle School Student'), ('H', 'High School Student'), ('E', 'Homeschooled'), ('U', 'Undergraduate'), ('G', 'Graduate Student'), ('T', 'Teacher'), ('P', 'Security Professional'), ('Y', 'CTF Hobbyist'), ('O', 'Other')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='country',
            field=django_countries.fields.CountryField(default='US', max_length=2),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='window',
            name='codename',
            field=models.CharField(help_text='Human-readable identifier', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^\\w*$Only alphanumeric characters and underscores are allowed.')]),
        ),
    ]
