# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 02:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ctflex', '0009_auto_20160308_0135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ctfproblem',
            options={'verbose_name': 'Problem'},
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='posted',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='unread_announcements',
        ),
        migrations.AddField(
            model_name='announcement',
            name='body_html',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='competitors',
            field=models.ManyToManyField(blank=True, related_name='unread_announcements', to='ctflex.Competitor'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 19, 2, 41, 45, 210440, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='title_html',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='announcement',
            name='window',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ctflex.Window'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='problems',
            field=models.ManyToManyField(blank=True, to='ctflex.CtfProblem'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ctfproblem',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
