# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-10 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctflex', '0009_auto_20160402_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctfproblem',
            name='sort_last',
            field=models.BooleanField(default=False),
        ),
    ]
