# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-10 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctflex', '0010_ctfproblem_sort_last'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
