# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-20 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctflex', '0010_auto_20160318_2241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='time',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='background',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='country',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='state',
        ),
        migrations.AddField(
            model_name='team',
            name='background',
            field=models.CharField(choices=[('S', 'Middle-school/High-school'), ('O', 'Other (ineligible for prizes)')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='team',
            name='country',
            field=models.CharField(choices=[('U', 'United States of America'), ('O', 'Other (ineligible for prizes)')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='solve',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
