# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctflex', '0011_auto_20160410_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solve',
            name='flag',
            field=models.CharField(max_length=200),
        ),
    ]
