# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-01 02:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctflex', '0011_auto_20160320_0357'),
        ('ctflex', '0005_auto_20160326_2341'),
    ]

    operations = [
    ]
