# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctflex', '0012_auto_20160414_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='flag',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
