# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctflex', '0013_auto_20160414_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='standing',
            field=models.CharField(choices=[('G', 'Good'), ('D', 'Disqualified'), ('I', 'Invisible')], default='G', max_length=1),
        ),
    ]
